language: node_js

node_js: stable

cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli
  - npm install -g hexo --registry=https://registry.npm.taobao.org

install:
  - npm install

script:
  - sed -i "s/valine_app_id/${valine_app_id}/g" ./themes/icarus/_config.yml
  - sed -i "s/valine_app_key/${valine_app_key}/g" ./themes/icarus/_config.yml
  - npm ls --depth 0
  - hexo clean
  - hexo g && gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "bytepoem"
  - git config user.email "laiyuancai@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${DEPLOY_KEY}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/bytepoem/blog.git

notifications:
  email:
    - laiyuancai@gmail.com
  on_success: change
  on_failure: always
